name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install modules
        run: bun install
      - name: Run prettier + eslint + ts typecheck + tests
        run: bun checkall
